apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
- "RequestReceived"
rules:
- level: Metadata
  resources:
  - group: ""
    resources:
    - "events"
- level: RequestResponse
  verbs:
  - create
  - update
  - patch
- level: Metadata
